### ISSUE TITLE
FlutterRun apparently not working on windows

### ISSUE THREAD

**Issue by lfrigodesouza** [thosakwe/vim-flutter#25]
Hi! I'm having some trouble setting up my vim to work with flutter. I have my flutter project opened, my emulator is running, but when I run FlutterRun on my vim nothing happens, just the Flutter_Output is opened, but my project won't start. Am I doing something wrong?
I'm on Windows, and while using VSCode everything works fine; and other commands also work on vim, like FlutterEmulators or FlutterEmulatorsLaunch, but not FlutterRun.

Is there any log of some sort that I can check to try and see whats happening?
Thanks!

![image](https://user-images.githubusercontent.com/19676697/73504930-c57f1800-43af-11ea-83c4-5920743e07e4.png)

**Comment by thosakwe** [comment]
What Vim version are you running?

**Comment by lfrigodesouza** [comment]
I tried in both versions 8.1.1 and 8.2, with terminal vim and gVim, and the result is the same.

**Comment by thosakwe** [comment]
That's weird. FlutterEmulators+FlutterEmulatorsLaunch just run commands directly, but FlutterRun, FlutterHotReload, etc., will send keys to a running `flutter` process, and display the output in the buffer.

How long do you keep the __Flutter_Output__ window open before closing it? It may be that the process is just taking a long time to show output.

**Comment by lfrigodesouza** [comment]
I left it open for almost an hour, and nothing changed.
When I execute `flutter run` on a terminal it takes around 3 minutes to start the application on the emulator, so I don't see how it could take more time than that.

**Comment by thosakwe** [comment]
I'll try it again on my end, but I haven't been able to reproduce this. That being said, I'm running on Mac. But also, the scripts aren't using any platform specific functionality.

Is `flutter` in your PATH?

**Comment by lfrigodesouza** [comment]
Yes, it is on the PATH. I cal call `flutter run` on the cmd or Power Shell and it will start the application.

I added a call to `job_info(g:flutter_job)` just after the job is started, and this is the output:
`{'status':'fail', 'cmd':['flutter','run'], 'stoponexit':'term', 'tty_out': '', 'exitval':0, 'exit_cb': 'flutter#_exit_cb', 'tty_in' : '', 'channel': 'channel fail', 'tty_type': '', 'process':0}`

So apparently the channel is failing to open, but I'm not being able to figure out why.

**Comment by thosakwe** [comment]
What happens if you manually try to start a `flutter` job? Also, I guess the plugin should display some sort of error if the job fails to start.

**Comment by lfrigodesouza** [comment]
Ok, I managed to make it work!
I changed my flutter_command variable to include a call to the 'cmd' like this:
`:let g:flutter_command = 'cmd.exe /c flutter'`

And then it worked like a charm, the hot-reload and everything!

**Comment by thosakwe** [comment]
Wow, that's interesting. Maybe on Windows, it should default to using `cmd.exe`?

**Comment by lfrigodesouza** [comment]
I think this pull request solves this issue: https://github.com/thosakwe/vim-flutter/pull/17
Just tested it out, changing my flutter_command back to only `flutter`, and it worked as well.

**Comment by insidewhy** [comment]
@lfrigodesouza This should be solved in the latest code now, please reopen this issue if it doesn't work.
