### ISSUE TITLE
Feature Request: open Flutter Output at bottom by default instead of top

### ISSUE THREAD

**Issue by sollymay** [thosakwe/vim-flutter#33]
Hey @thosakwe! Hope you are doing great and thank you for taking the time to develop this awesome plugin!

I wanted to see if its possible to add an option in the future to make the Flutter Output split to appear at the bottom of the already opened editor screen instead of at the top. This would totally change the way I work (before I used to have an open terminal window at the bottom and on changes, I would just go down to the terminal window and run a hot restart/reload, so I already have the memory of going down lol).

Thank you!

**Comment by thosakwe** [comment]
FlutterSplit just uses the :sp command. To affect the position of split windows, you have to set `splitbelow` in your Vim configuration. Try running `:h splitbelow`.

**Comment by sollymay** [comment]
Awesome! I did not know about that configuration! just added it to .vimrc so it applies each time this is executed.

Thank you!
