### ISSUE TITLE
autocmd chaining spawns two windows instead of one

### ISSUE THREAD

**Issue by CodingLappen** [thosakwe/vim-flutter#36]
Hello,

I have the following autocommand

autocmd Filetype .dart exe "FlutterRun" | exe "FlutterVSplit" 

Why does this spawn two additional windows with the output buffer, instead of one.
I am curious how to fix this, because chaining | exe "clo 2" does close both additional windows. 

Thanks in advance.

**Comment by thosakwe** [comment]
FlutterRun will open a new window, so you don't need to add an additional FlutterSplit call.
