### ISSUE TITLE
Error: Flutter is not running

### ISSUE THREAD

**Issue by mrkvn** [thosakwe/vim-flutter#37]
`Neovim: v0.4.4`

I'm getting this error even if flutter is running.
```
Error detected while processing function flutter#hot_reload[1]..flutter#send:
line    2:
Flutter is not running.
```

There's no error though if I ran flutter inside neovim using `:FlutterRun`

Is this the intended behavior? Having to run `:FlutterRun`  in order for the plugin to recognize that flutter is running? If yes, I suggest that the plugin should still work even if flutter was run outside of vim/neovim. And if not, then this is a bug.

**Comment by thosakwe** [comment]
Yes, this is the intended behavior. This plugin communicates with a `flutter` process via STDIO. 

I don't think it will be very easy to get the plugin to communicate with processes that it didn't spawn.

**Comment by mrkvn** [comment]
Not sure if it's ok to link it here, but [here](https://github.com/hankchiutw/flutter-reload.vim/blob/master/plugin/reload.vim) it is anyway. He's reloading flutter using the command:
```
kill -SIGUSR1 "$(pgrep -f flutter_tools.snapshot\ run)" &> /dev/null
```
I'm not really familiar with the command but based on my search, it's sending signal to a process, which is `flutter` in this case. Not sure how it really works and how that command make flutter reload but it works.

I'm just starting with flutter now so I don't know which commands I need for vim/flutter integration in the future. I just need the hot reload for now so I'm going with that simple script.

Feel free to close this issue.
