### ISSUE TITLE
fvm Support

### ISSUE THREAD

**Issue by tobinharris** [thosakwe/vim-flutter#38]
Hi!

Nice plug. Would it be difficult to add `fvm` support so that vim-flutter uses that if detected?

**Comment by thosakwe** [comment]
Try `let g:flutter_command = 'fvm'` in your vimrc.

**Comment by 3to8-decoder** [comment]
setting it to 'fvm' doesn't work, it should be 'flutter fvm'

however, current code does not support g:flutter_command with spaces in it.
Very easy to change though. I fixed it in a fork.
See merge request: https://github.com/thosakwe/vim-flutter/pull/45
