### ISSUE TITLE
autoscroll?

### ISSUE THREAD

**Issue by 3nt3** [thosakwe/vim-flutter#39]
Can you make the output of `:FlutterRun` automatically scroll to the bottom when new lines appear?

**Comment by insidewhy** [comment]
Yeah this is actually super annoying :D I'll see if I can fix it.

**Comment by insidewhy** [comment]
@3nt3 Implemented this here https://github.com/thosakwe/vim-flutter/pull/42

You can use `insidewhy/vim-flutter` as your repo if you wanna use it.

**Comment by insidewhy** [comment]
In this repo now.

**Comment by thosakwe** [comment]
Thanks @insidewhy for the help!

**Comment by insidewhy** [comment]
@thosakwe Thanks for trusting me with the access, I won't let you down!
