### ISSUE TITLE
Hot reload fails

### ISSUE THREAD

**Issue by teekey-dev** [thosakwe/vim-flutter#4]
Hello! I just started trying to build an app with flutter with vim.
I installed this plugin and wanted to see the hot reload function when I save the main.dart file. But I got the following error. 
I am now using `neovim v0.2.2` on `OSX`.

```sh
Error detected while processing function flutter#hot_reload[1]..flutter#send:
line    4:
E117: Unknown function: job_getchannel
E15: Invalid expression: job_getchannel(g:flutter_job)
```

Thanks in advance!

**Comment by thosakwe** [comment]
As per the README, this is a Vim8 plug-in. However, @paulreimer recently added Neovim support for this plug-in; you might want to reach out to him.

See the following check: https://github.com/paulreimer/vim-flutter/blob/c71e1fdb26e4f137e20244f32438721bb3bea669/autoload/flutter.vim#L79-L95

It uses `has('nvim')` to determine if you are using Neovim. So, for some reason or another, that flag is not present in your Neovim.

**Comment by paulreimer** [comment]
Actually, I think this is legit, I can make another patch for neovim.

**Comment by paulreimer** [comment]
I made PR #5 -- I had made that patch on my copy but it didn't make it into the other PR, sorry about that.
