### ISSUE TITLE
Problem executing FlutterRun when not in the root of the project

### ISSUE THREAD

**Issue by elC0mpa** [thosakwe/vim-flutter#43]
First of all, I would like to thank you for this excellent package. I am having he following problem:
![image](https://user-images.githubusercontent.com/53531665/161995913-81a59d55-909e-463a-94d7-d7582bf02bdd.png)
This is the root of my github repository. The problem is that **goheay_customer** and **goheay_driver** are two diifferent apks related to the same project. The point is that when I try to execute the following command:
*FlutterRun --flavor dev -t goheavy_customer/lib/main_dev.dart* I get the following error:
![image](https://user-images.githubusercontent.com/53531665/162000656-f7f4de1f-c697-41f2-8513-68f97cbadd4d.png)
I would like to know if there is any alternative for me to use this command and still open the project root, which is not the flutter project root. Thanks in advance

**Comment by insidewhy** [comment]
Is this something you can solve with regular `flutter run`?

**Comment by insidewhy** [comment]
I guess this plugin is constrained by whatever flutter can do in general. It will forward whatever args you want to over to `flutter run`.

**Comment by emmanuelrosa** [comment]
What about having some flag to instruct FlutterRun to cd to a given directory prior to running `flutter run`?

When using a monorepo/workspace, such as a serverpod project, having the VIM working directory be the root of the monorepo allows the Dart language server integration (via vim-lsc) to work, but it breaks FlutterRun. Changing the root directory to the Flutter project fixes FlutterRun, but breaks the Dart language server. This happens with both VIM's `:cd` and `:tcd`.
