### ISSUE TITLE
Hot reload is not working for vim auto command update

### ISSUE THREAD

**Issue by jithusjacob** [thosakwe/vim-flutter#44]
I have a auto command to save dart file when insert leave
augroup AUTOSAVE
    au!
     autocmd InsertLeave,TextChanged,FocusLost * silent! update
    augroup END

But HotRelaod is not triggered until I manually write it. (:w).

**Comment by insidewhy** [comment]
This can't work, flutter needs the file to be written so it can see the updated content.
