### ISSUE TITLE
hot reload not working for linux device

### ISSUE THREAD

**Issue by laoshaw** [thosakwe/vim-flutter#47]
I'm running `flutter run` using vim-flutter as vim plugin, to reload my changes after save, I need hit `r` at the terminal to reload, it seems vim's save could not trigger it. I checked g:flutter_hot_reload_on_save to be 1. I develop on ubuntu and the app is also built for linux as the target platform. is hot-reload only for android and ios?

**Comment by insidewhy** [comment]
It works by sending the `r` so it should work anywhere.

> I'm running flutter run using vim-flutter as vim plugin,

What command are you using specifically?

**Comment by laoshaw** [comment]
I just saved the modified file and expected it triggers a hot reload, and it did not.

**Comment by insidewhy** [comment]
I assume you used `:FlutterRun` or `:FlutterAttach`?

**Comment by laoshaw** [comment]
Not really, do  I need to do that? I did 'flutter run' on a terminal, then use vim to edit source code and save the modifications, thought that 'save' will trigger a hot reload. At least that's how my javascript works: `npm run dev` from a terminal, then edit any file with vim and each save will lead to a hot reload

**Comment by insidewhy** [comment]
> do I need to do that?

Yes, attach if you already have a flutter run in your terminal, run to run flutter within vim itself.

> At least that's how my javascript works: npm run dev from a terminal, then edit any file with vim and each save will lead to a hot reload

That's because whatever framework you are using has a file watcher built into it. Flutter doesn't have that.
