### ISSUE TITLE
Help on FlutterMenu

### ISSUE THREAD

**Issue by sutrisnob45** [thosakwe/vim-flutter#7]
could you please add some detail on how to enable the FlutterMenu?
i'm a newbie when it come to vim, so any help appreciated

**Comment by thosakwe** [comment]
It's just a function, so all you have to do is `call FlutterMenu`. You can
include this in a vimrc:

```vim
autocmd FileType dart :call FlutterMenu()
```

**Comment by thosakwe** [comment]
It's just a function, so all you have to do is `call FlutterMenu`. You can include this in a vimrc:

```vim
autocmd FileType dart :call FlutterMenu()
```
